In [4]:

1.A database is an organized collection ofbstructured information, or data, typically stored electronically in a computer system.
SQL database is called as structured query language, NOSQL is known as not only structured query language. sql is a relational database and nosql is non relational database.
 e.g. sql :- mysql, nosql:- mongodb, cassandra etc
    
    
2.DDL means data definition language, this is used to define the database schema. 
  CREATE- this command is used to create the database or its objects(like table,index,function etc).
import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="abc",
  password="password"
)
print(mydb)
mycursor = mydb.cursor()
mycursor.execute("CREATE DATABASE if not exists test20") 

 DROP-This command is used to delete objects from the database.
import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="abc",
  password="password"
) 
print(mydb)
mycursor = mydb.cursor()
mycursor.execute("CREATE TABLE if not exists test20.test_table(c1 INT, c2 VARCHAR(10), c3 FLOAT, c4 INT , c5 VARCHAR(30))")
mycursor.execute("DROP TABLE test20.test_table")

 ALTER- This is used to alter the structure of the database.
import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="abc",
  password="password"
) 
print(mydb)
mycursor = mydb.cursor()
mycursor.execute("CREATE TABLE if not exists test20.test_table(c1 INT, c2 VARCHAR(10), c3 FLOAT, c4 INT , c5 VARCHAR(30))")
mycursor.execute("ALTER TABLE test20.test_table ADD c6 INT")
  TRUNCATE-THis is used to remove all records from a table, includeing all spaces allocated for the records are removed.
import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="abc",
  password="password"
) 
print(mydb)
mycursor = mydb.cursor()
mycursor.execute("TRUNCATE TABLE test20.test_table")
3.DML means data manipulation language.
INSERT-allows you to add.
import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="abc",
  password="password"
) 
print(mydb)
mycursor = mydb.cursor()
mycursor.execute("INSERT into test20.test_table2 values(122,'satya',23.33,100)")
mydb.commit()
UPDATE is used to modify the records in table.
import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="abc",
  password="password"
) 
print(mydb)
mycursor = mydb.cursor()
mycursor.execute("UPDATE test20.test_table2 SET c1=1000 WHERE c1=1")
DELETE is used   to delete elements
import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="abc",
  password="password"
) 
print(mydb)
mycursor = mydb.cursor()
mycursor.execute("DELETE FROM test20.test_table2 WHERE(c1=122)")
4.DQL means data query language. SELECT statement is used to select data from database.
import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="abc",
  password="password"
) 
print(mydb)
mycursor = mydb.cursor()
mycursor.execute("SELECT c1,c2 FROM test20.test_table2")
myresult=mycursor.fetchall()
for x in myresult:
  print(x)
5. A primary key is used to ensure data in the specific column is unique. A foreign key is a column or group of columns in a relational database table that provides a link between data in two tables.
6.import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="abc",
  password="password"
) 
print(mydb)
mycursor = mydb.cursor()
mycursor.execute(import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="abc",
  password="password"
) 
print(mydb)
mycursor = mydb.cursor()
->cursor in sql server is a database object that allows us to retrive each row at a time and manipulate its data. a cursor is nothing more than a pointer to a row.
->execute method runs an sql statement.

ModuleNotFoundError: No module named 'mysql'